import { Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PrismaService } from '../../database/prisma.service';

@Injectable()
export class ReportsService {
  constructor(private prisma: PrismaService) {}

  async generateDailySiteReport(siteId: string): Promise<Buffer> {
    const site = await this.prisma.site.findUnique({
      where: { id: siteId },
      include: { client: true },
    });

    if (!site) throw new NotFoundException('Site not found');

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    const [
      todayAttendance,
      totalGuards,
      todayIncidents,
      lateCount,
      absentCount,
      todayPatrols,
    ] = await Promise.all([
      this.prisma.attendance.count({
        where: {
          siteId,
          checkInTime: { gte: today, lt: tomorrow },
          status: { not: 'ABSENT' },
        },
      }),
      this.prisma.guard.count({
        where: { assignedSiteId: siteId, status: 'ACTIVE' },
      }),
      this.prisma.incident.count({
        where: { siteId, reportedAt: { gte: today, lt: tomorrow } },
      }),
      this.prisma.attendance.count({
        where: {
          siteId,
          checkInTime: { gte: today, lt: tomorrow },
          isLate: true,
        },
      }),
      this.prisma.attendance.count({
        where: {
          siteId,
          checkInTime: { gte: today, lt: tomorrow },
          status: 'ABSENT',
        },
      }),
      this.prisma.patrolRecord.count({
        where: {
          route: { siteId },
          startTime: { gte: today, lt: tomorrow },
          status: 'COMPLETED',
        },
      }),
    ]);

    const recentIncidents = await this.prisma.incident.findMany({
      where: { siteId, reportedAt: { gte: today } },
      take: 10,
      orderBy: { reportedAt: 'desc' },
      select: { title: true, incidentType: true, severity: true },
    });

    const pdfBuffer: Buffer = await new Promise((resolve) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(20).text('SPECTRA OPS', { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).text('Daily Operations Report', { align: 'center' });
      doc.moveDown(2);

      // Site Info
      const clientName = site.client?.companyName || 'Deleted Client';
      doc.fontSize(12).font('Helvetica-Bold').text(`Site: ${site.name}`);
      doc.font('Helvetica').text(`Client: ${clientName}`);
      doc.text(`Date: ${new Date().toLocaleDateString()}`);
      doc.text(`Risk Level: ${site.riskLevel}`);
      doc.moveDown(2);

      // Attendance Summary
      doc.fontSize(14).font('Helvetica-Bold').text('Attendance Summary');
      doc
        .font('Helvetica')
        .text(`Present: ${todayAttendance} / ${totalGuards}`);
      doc.text(`Late: ${lateCount}`);
      doc.text(`Absent: ${absentCount}`);
      doc.text(`Today's Patrols Completed: ${todayPatrols}`);
      doc.moveDown();

      // Incident Log
      doc.fontSize(14).font('Helvetica-Bold').text('Incident Log');
      if (recentIncidents.length === 0) {
        doc.font('Helvetica').text('No incidents reported today.');
      } else {
        for (const inc of recentIncidents) {
          doc
            .font('Helvetica')
            .text(`- [${inc.severity}] ${inc.incidentType}: ${inc.title}`);
        }
      }
      doc.moveDown();

      // Footer
      doc
        .fontSize(10)
        .fillColor('gray')
        .text(
          'This document is auto-generated by Spectra Operations Intelligence Platform.',
          50,
          750,
          { align: 'center', width: 500 },
        );

      doc.end();
    });

    return pdfBuffer;
  }

  async generateWeeklySiteReport(siteId: string): Promise<Buffer> {
    const site = await this.prisma.site.findUnique({
      where: { id: siteId },
      include: { client: true },
    });
    if (!site) throw new NotFoundException('Site not found');

    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    weekAgo.setHours(0, 0, 0, 0);

    const [
      weeklyAttendance,
      weeklyIncidents,
      patrolCount,
    ] = await Promise.all([
      this.prisma.attendance.count({
        where: { siteId, checkInTime: { gte: weekAgo } },
      }),
      this.prisma.incident.findMany({
        where: { siteId, reportedAt: { gte: weekAgo } },
        orderBy: { reportedAt: 'desc' },
        select: { title: true, incidentType: true, severity: true, reportedAt: true },
      }),
      this.prisma.patrolRecord.count({
        where: { route: { siteId }, startTime: { gte: weekAgo } },
      }),
    ]);

    const pdfBuffer: Buffer = await new Promise((resolve) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      doc.fontSize(20).text('SPECTRA OPS', { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).text('Weekly Operations Report', { align: 'center' });
      doc.moveDown(2);

      const clientName = site.client?.companyName || 'Deleted Client';
      doc.fontSize(12).font('Helvetica-Bold').text(`Site: ${site.name}`);
      doc.font('Helvetica').text(`Client: ${clientName}`);
      doc.text(`Period: ${weekAgo.toLocaleDateString()} - ${new Date().toLocaleDateString()}`);
      doc.text(`Risk Level: ${site.riskLevel}`);
      doc.moveDown(2);

      doc.fontSize(14).font('Helvetica-Bold').text('Weekly Summary');
      doc.font('Helvetica').text(`Total Attendance Records: ${weeklyAttendance}`);
      doc.text(`Total Patrols Completed: ${patrolCount}`);
      doc.text(`Total Incidents Reported: ${weeklyIncidents.length}`);
      doc.moveDown();

      doc.fontSize(14).font('Helvetica-Bold').text('Incident Log');
      if (weeklyIncidents.length === 0) {
        doc.font('Helvetica').text('No incidents reported this week.');
      } else {
        for (const inc of weeklyIncidents) {
          doc.font('Helvetica')
            .text(`- [${inc.severity}] ${inc.incidentType}: ${inc.title} (${new Date(inc.reportedAt).toLocaleDateString()})`);
        }
      }
      doc.moveDown();

      doc.fontSize(10).fillColor('gray')
          .text('This document is auto-generated by Spectra Operations Intelligence Platform.', 50, 750, { align: 'center', width: 500 });

        doc.end();
      });

      return pdfBuffer;
    }

    async generateAllDailyReports(organizationId: string) {
      const sites = await this.prisma.site.findMany({
        where: { organizationId },
        select: { id: true, name: true },
      });

      const results: { siteId: string; siteName: string; success: boolean; error?: string }[] = [];

      for (const site of sites) {
        try {
          await this.generateDailySiteReport(site.id);
          results.push({ siteId: site.id, siteName: site.name, success: true });
        } catch (err: any) {
          results.push({ siteId: site.id, siteName: site.name, success: false, error: err.message });
        }
      }

      return {
        generated: results.filter(r => r.success).length,
        failed: results.filter(r => !r.success).length,
        details: results,
      };
    }

    async generateGuardDailyReport(guardId: string): Promise<Buffer> {
      const guard = await this.prisma.guard.findUnique({
        where: { id: guardId },
        include: { assignedSite: true },
      });
      if (!guard) throw new NotFoundException('Guard not found');

      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const tomorrow = new Date(today);
      tomorrow.setDate(tomorrow.getDate() + 1);

      const todaysAttendance = await this.prisma.attendance.findFirst({
        where: { guardId, checkInTime: { gte: today, lt: tomorrow } },
      });

      const recentPatrols = await this.prisma.patrolRecord.findMany({
        where: { guardId },
        take: 5,
        orderBy: { startTime: 'desc' },
      });

      const totalAttendances = await this.prisma.attendance.count({ where: { guardId } });
      const lateCount = await this.prisma.attendance.count({ where: { guardId, isLate: true } });

      const pdfBuffer: Buffer = await new Promise((resolve) => {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const buffers: Buffer[] = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        doc.fontSize(20).text('SPECTRA OPS', { align: 'center' });
        doc.moveDown();
        doc.fontSize(16).text('Guard Daily Report', { align: 'center' });
        doc.moveDown(2);

        doc.fontSize(12).font('Helvetica-Bold').text(`Guard: ${guard.fullName}`);
        doc.font('Helvetica').text(`Site: ${guard.assignedSite?.name || 'Unassigned'}`);
        doc.text(`Shift: ${guard.currentShift}`);
        doc.text(`Date: ${new Date().toLocaleDateString()}`);
        doc.text(`Performance Score: ${guard.performanceScore}%`);
        doc.moveDown(2);

        doc.fontSize(14).font('Helvetica-Bold').text('Attendance Summary');
        doc.font('Helvetica').text(`Total Records: ${totalAttendances}`);
        doc.text(`Late Arrivals: ${lateCount}`);
        doc.text(`Attendance Rate: ${totalAttendances > 0 ? Math.round(((totalAttendances - lateCount) / totalAttendances) * 100) : 100}%`);
        doc.moveDown();

        if (todaysAttendance) {
          doc.fontSize(14).font('Helvetica-Bold').text('Today\'s Activity');
          doc.font('Helvetica').text(`Check-in: ${todaysAttendance.checkInTime.toLocaleTimeString()}`);
          doc.text(`Check-out: ${todaysAttendance.checkOutTime?.toLocaleTimeString() || 'Still on duty'}`);
          doc.text(`Status: ${todaysAttendance.status}`);
          doc.moveDown();
        }

        doc.fontSize(14).font('Helvetica-Bold').text('Recent Patrols');
        if (recentPatrols.length === 0) {
          doc.font('Helvetica').text('No patrol records found.');
        } else {
          for (const p of recentPatrols) {
            doc.font('Helvetica').text(`- ${p.status}: ${Math.round(p.completionPercentage)}% complete (${new Date(p.startTime).toLocaleDateString()})`);
          }
        }
        doc.moveDown();

        doc.fontSize(10).fillColor('gray')
          .text('This document is auto-generated by Spectra Operations Intelligence Platform.', 50, 750, { align: 'center', width: 500 });

        doc.end();
      });

      return pdfBuffer;
    }
  }
